@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Search Figure By Category And Keyword

actor "CRM Collaborator" as USER
participant ":System" as System

autonumber

USER -> System : Search Figure By Category And Keyword
activate System

System --> USER : Request Category Name and Keyword
deactivate System

USER -> System : Provide Category Name and Keyword
activate System

System --> USER : Show Figure List
deactivate System

@enduml
