persistence.persistenceUnit=SHODRONE_PU

persistence.repositoryFactory=lapr4.JpaRepositoryFactory
#persistence.repositoryFactory=lapr4.InMemoryRepositoryFactory

eapli.framework.pubsub.instanceKey=backoffice.app.001
eapli.framework.pubsub.poolInterval=5000

ui.menu.layout=horizontal

UseEventfulControllers=true