@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Add Figure Proposal

actor "CRM Collaborator" as USER
participant ":System" as System

autonumber

USER -> System : Add Figure Proposal
activate System

System --> USER : Show list of show proposals
deactivate System

USER -> System : Select show proposal
activate System

System --> USER : Show list of figures
deactivate System

USER -> System : Select figure
activate System

System --> USER : Request coordinates
deactivate System

USER -> System : Provide coordinates
activate System

System --> USER : Display success or error message
deactivate System

@enduml
