persistence.persistenceUnit=SHODRONE_PU

persistence.repositoryFactory=lapr4.JpaRepositoryFactory
#persistence.repositoryFactory=lapr4.InMemoryRepositoryFactory

ui.menu.layout=horizontal

UseEventfulControllers=true