@startuml
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

actor "Show Designer or CRM Collaborator" as Actor
participant ListFigureCategoryUI as UI <<presentation>>
participant ListFigureCategoryController as Controller <<application>>
participant ListFigureCategoryService as svc <<application>>
participant FigureCategoryDTOParser as Parser <<application>>
database FigureCategoryRepository as Repo <<repository>>

Actor --> UI: Request List Figure Category
activate UI

    UI -> Controller: listFigureCategories()
    activate Controller

    note right of Controller : hidden authorization user guarantee \n(see specific diagram)

        Controller -> svc: allFigureCategories()
        activate svc

            note right of svc : Simplified persistence\n(see specific diagram)

                    svc -> Repo : findAll()
                    activate Repo

                    Repo --> svc : categories
                    deactivate Repo

                    svc -> Parser : transformToDTO(categories)
                    activate Parser

                    Parser --> svc : categoriesDTO
                    deactivate Parser

        svc --> Controller: categoriesDTO
        deactivate svc

    Controller --> UI: categoriesDTO
    deactivate Controller

    UI --> Actor: Display list of Categories or error

deactivate UI
@enduml