@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Change Figure Category

actor "Show Designer" as USER
participant ":System" as System

autonumber

USER -> System : Request to Change Figure Category
activate System

System --> USER : Display list of categories
deactivate System

USER -> System : Select Category
activate System

System --> USER : Display Category Details
deactivate System

loop For each attribute (Name, Description)
    USER -> System : Provide new value or skip
    activate System
    System --> USER : Confirm update or skip
    deactivate System
end

System --> USER : Figure Category updated info or error message
deactivate System

@enduml
