@startuml
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

actor "Show Designer" as Actor
participant ActivateFigureCategoryUI as UI <<presentation>>
participant ActivateFigureCategoryController as Controller <<application>>
participant ListFigureCategoryService as svc <<application>>
participant FigureCategoryDTOParser as Parser <<application>>
participant FigureCategoryDTO as Dto <<dto>>
participant FigureCategory as Domain <<domain>>
database FigureCategoryRepository as Repo <<repository>>

Actor --> UI: Activate Figure Category
activate UI

    UI -> Controller: inactiveFigureCategories()
    activate Controller

    note right of Controller : hidden authorization user guarantee \n(see specific diagram)

        Controller -> svc: allInactiveFigureCategories()
        activate svc

            note right of svc : Simplified persistence\n(see specific diagram)

                    svc -> Repo : findAllInactive()
                    activate Repo

                    Repo --> svc : inactiveCategories
                    deactivate Repo

                    svc -> Parser : transformToDTO(inactiveCategories)
                    activate Parser

                    Parser --> svc : inactiveCategoriesDTO
                    deactivate Parser

        svc --> Controller: inactiveCategoriesDTO
        deactivate svc

    Controller --> UI: inactiveCategoriesDTO
    deactivate Controller

    UI --> Actor: Show Inactive Categories

    Actor --> UI: Select Category

        UI -> Controller: activateFigureCategory(categoryDTO)
        activate Controller

            Controller -> Parser: valueOf(categoryDTO)
            activate Parser

                    Parser -> Dto: getName()
                    activate Dto

                    Dto --> Parser: categoryName
                    deactivate Dto

                    Parser -> Repo: ofIdentity(categoryName)
                    activate Repo

                    Repo --> Parser: category
                    deactivate Repo

            Parser --> Controller: category
            deactivate Parser

            Controller -> Domain: activate
            activate Domain

            Domain --> Controller: void
            deactivate Domain

            Controller -> Domain: toDTO()
            activate Domain

            Domain --> Controller: categoryDTO
            deactivate Domain

        Controller --> UI: categoryDTO
        deactivate Controller

    UI --> Actor: Display Category Info or error

deactivate UI
@enduml