@startuml
skinparam classAttributeIconSize 0
hide empty attributes

package "Presentation" {
    class EnableUserUI <<presentation>> {
    }
}

package "Application" {
    class EnableUserController <<application>> {
        +disabledUsers() : Iterable<ShodroneUserDTO>
        +enableUser(shodroneUserDTO) : SystemUser
    }

    class UserManagementService <<application>> {
        +activateUser(systemUser) : SystemUser
    }

    class AuthzRegistry <<utility>> {
        +userService() : UserManagementService
    }

    class ShodroneUserDTOParser <<application>> {
        +transformToDTO(inactiveUsers)
        +valueOf(shodroneUserDTO)
    }
}

package "DTO" {
    class ShodroneUserDTO <<dto>> {
    }
}

package "Domain" {

    package "<<aggregate>> ShodroneUser" {
        class ShodroneUser <<entity>> <<root>> {
        }

        class ShodroneEmail <<value object>> <<id>> {
        }

        class PhoneNumber <<value object>> {
        }
    }

    package "<<aggregate>> SystemUser" {
        class SystemUser <<entity>> <<root>> {
            -active : boolean
        }

        class Username <<value object>> <<id>> {
        }

        class Password <<value object>> {
        }

        class Name <<value object>> {
        }

        class EmailAddress <<value object>> {
        }

        class RoleSet {
        }

        interface Set <<interface>> {
        }

        class RoleAssigment <<entity>> {
        }

        class Role <<value object>> {
        }
    }
}

package "Persistence" {
    class ShodroneUserRepository <<repository>> {
        +findAllDisabled() : Iterable<ShodroneUser>
    }
}

EnableUserUI --> EnableUserController
AuthzRegistry --> UserManagementService : userService
EnableUserController ..> AuthzRegistry
EnableUserController ..> UserManagementService : userSvc
UserManagementService --> SystemUser : systemUser
EnableUserController --> ShodroneUserRepository : repo
EnableUserController --> ShodroneUserDTOParser : parser

ShodroneUserDTOParser --> ShodroneUserDTO : dto

ShodroneUser --> ShodroneEmail
ShodroneUser --> PhoneNumber
ShodroneUser --> SystemUser : has

SystemUser --> Username
SystemUser --> Password
SystemUser --> Name
SystemUser --> EmailAddress
SystemUser --> RoleSet
RoleSet ..|> Set
Set ..> RoleAssigment
RoleAssigment --> Role

@enduml
